# Custom Network definieren

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network

  dbsettle:
    image: postgres:15
    container_name: dbsettle
    environment:
      - POSTGRES_DB=settle_db
      - POSTGRES_USER=noss
      - POSTGRES_PASSWORD=noss1
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noss -d settle_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend-settle:
    build: .
    container_name: backend-settle
    ports:
      - "3500:3500"
      - "4000:4000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    environment:
      - NODE_ENV=production
      - PORT=3500
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - DATABASE_URL=postgresql://noss:noss1@dbsettle:5432/settle_db?schema=public
      - OLLAMA-HOST=http://ollama:11434
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3500/test"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./localhost.pem:/app/localhost.pem
      - ./localhost-key.pem:/app/localhost-key.pem
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  ollama-data:
